name = "backend"
compatibility_date = "2024-09-27"
compatibility_flags = [ "nodejs_compat" ]

 [vars]
# MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNjU0N2UyM2YtMDQ4MS00NzZhLWI1NGQtNGU5MjYzZmYyOTU2IiwidGVuYW50X2lkIjoiNDI0MTkwODU2YjE0Yjc4NGY4NDZlZjE4ZWVkZTZhNDI5NjMwOWQ5NzlhYWFjODg1MjcxYTI4MWI5M2FiYmM5NSIsImludGVybmFsX3NlY3JldCI6ImU1NzgyZmI5LTcwOTUtNGEyNy05MjYzLTJjMGEwYmUwNzdmOCJ9.Fg8mnBu-jCTVG5TvutprVrstdQw1Cn7WicTcuEEIkHc"
JWT_SECRET="car"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"